### ISSUE TITLE
Setting custom connection name via client_properties doesn't work when connecting using an amqp:// URL

### ISSUE THREAD

**Issue by zackelan** [mosquito/aio-pika#301]
Repro:

```
import asyncio
import aio_pika


async def main():
    # named connection using URL (works)
    abc_conn = await aio_pika.connect("amqp://localhost?name=ABC")

    # named connection using client properties (doesn't work)
    def_conn = await aio_pika.connect("amqp://localhost",
                                      client_properties={'connection_name': 'DEF'})

    # named connection using kwargs only (works)
    xyz_conn = await aio_pika.connect(host="localhost", name='XYZ')

    input('hit enter to close connections...')

    for conn in [abc_conn, def_conn, xyz_conn]:
        await conn.close()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

Expected:

https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.connect only gives the `client_properties` example of setting the connection name, so it's not obvious that it won't work when using a URL to connect, and the trick of using a `name` query parameter doesn't seem to be documented anywhere (only figured it out by reading through aiormq code).

Actual:

The snippet above will set the connection name in the RabbitMQ management UI as expected for ABC and XYZ, but not DEF.

Environment:

```
$ pip freeze
aio-pika==6.5.2
aiormq==3.2.1
idna==2.9
multidict==4.7.5
pamqp==2.3.0
yarl==1.4.2
```

Plus RabbitMQ 3.8.2

**Comment by rcjsuen** [comment]
Just hit this as well on RabbitMQ 3.8.2 with 6.6.1. The solution was to doubly nest `client_properties`.
```
connection = await aio_pika.connect_robust(
    broker_host,
    client_properties={
        "client_properties": {
            "connection_name": "..."
        }
    }
)
```

**Comment by JustinTArthur** [comment]
I've submitted a pull request upstream to get this fixed: mosquito/aiormq#94

**Comment by JustinTArthur** [comment]
For anyone waiting on this, it is fixed in the newly released aio-pika 7.x

**Comment by LECbg** [comment]
I'm using aio-pika 8.2.3 and I don't think it's fixed, `aio_pika.connect(...)` and `aio_pika.connect_robust(...)` pass `client_properties` only to `make_url(...)` and that function just returns the URL when given. Probably, when manually instantiating `Connection` and `RobustConnection`, passing `connection_name` works, but not for this methods.

**Comment by jdeflaux** [comment]
> I'm using aio-pika 8.2.3 and I don't think it's fixed, `aio_pika.connect(...)` and `aio_pika.connect_robust(...)` pass `client_properties` only to `make_url(...)` and that function just returns the URL when given. Probably, when manually instantiating `Connection` and `RobustConnection`, passing `connection_name` works, but not for this methods.
> 
> **EDIT:** After trying over and over again and debugging all over the 3 libraries, I've managed to set a custom name only without specifying the URL and by setting the property `name`, **NOT** `connection_name`.
> 
> i.e.:
> 
> ```python
> import aio_pika
> 
> await aio_pika.connect_robust(
>     host='localhost',
>     port=5672,
>     login='guest',
>     password='guest',
>     virtualhost='/',
>     ssl=False,
>     client_properties={
>         'name': 'Write connection'
>     }
> )
> ```

thanks it seems to be working with `name` rather than `connection-name`

**Comment by mosquito** [comment]
@nicksonthc fixed in #531

**Comment by nicksonthc** [comment]
> ```python
>  host='localhost',
>     port=5672,
>     login='guest',
>     password='guest',
>     virtualhost='/',
> ```

Thank mosquito.

Manage to get it work after remove url parameter , as mentioned by @LECbg 

>  cls._connection = await aio_pika.connect_robust(
                    host=rmq_host,
                    port=rmq_port,
                    login=rmq_user,
                    password=rmq_pass,
                    virtualhost=rmq_vhost,
                    client_properties={'name' : 'Nickson'})

**Comment by mosquito** [comment]
@nicksonthc so my local example script show the passed name as expected

```python

import asyncio

from aio_pika import connect_robust
from aio_pika.patterns import RPC


async def multiply(*, x: int, y: int) -> int:
    return x * y


async def main() -> None:
    connection = await connect_robust(
        "amqp://guest:guest@rabbitmq.local/?name=callee",
    )

    # Creating channel
    channel = await connection.channel(publisher_confirms=False)

    rpc = await RPC.create(channel)
    await rpc.register("multiply", multiply, auto_delete=True)

    await channel.set_qos(10)

    try:
        await asyncio.Future()
    finally:
        await connection.close()


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by nicksonthc** [comment]
> @nicksonthc so my local example script displays in rabbitmq managemtn ui the passed name as expected
> 
> ```python
> import asyncio
> 
> from aio_pika import connect_robust
> from aio_pika.patterns import RPC
> 
> 
> async def multiply(*, x: int, y: int) -> int:
>     return x * y
> 
> 
> async def main() -> None:
>     connection = await connect_robust(
>         "amqp://guest:guest@rabbitmq.local/?name=callee",
>     )
> 
>     # Creating channel
>     channel = await connection.channel(publisher_confirms=False)
> 
>     rpc = await RPC.create(channel)
>     await rpc.register("multiply", multiply, auto_delete=True)
> 
>     await channel.set_qos(10)
> 
>     try:
>         await asyncio.Future()
>     finally:
>         await connection.close()
> 
> 
> if __name__ == "__main__":
>     asyncio.run(main())
> ```

Hi, i tested the example you show is working `"amqp://guest:guest@rabbitmq.local/?name=callee"` too , thank @mosquito 

Below are the addtional info regard vhost.

For initialization with url parameter, i tested vhost parameter in the url as well due to my need.
url = f'amqp://{rmq_user}:{rmq_pass}@{rmq_host}:{rmq_port}/{rmq_vhost}/?name=callee'

When 
1. rmq_host = 
- e.g url = amqp://my-user:my-password@127.0.0.1:5672//?name=callee
- virtual host will become / in management UI which is expected
2. rmq_host = /
- e.g url = amqp://my-user:my-password@127.0.0.1:5672///?name=callee
- double //  , raise <class 'pamqp.exceptions.AMQPInternalError'> error 
3. rmq_host = /cluster-one
- e.g url = amqp://my-user:my-password@127.0.0.1:5672//cluster-one/?name=callee
- This working as well
